from .next_empty_cell import next_empty_cell
from .next_human_like_mrv_cell import next_human_like_mrv_cell
from .next_mrv_cell import next_mrv_cell

from .default_next_move import default_next_move
from .human_like_next_move import human_like_next_move